---
- name: Login to registry
  docker_login:
    registry: "{{ item }}"
    username: "{{ docker_insecure_user }}"
    password: "{{ docker_insecure_password }}"
    reauthorize: yes
  loop: "{{ docker_insecure_registries }}"