---
- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository for Ubuntu
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install dockerd for Ubuntu
  become: true
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  loop: [ "docker-ce", "docker-ce-cli", "containerd.io" ]

- name: Start docker daemon
  become: true
  service:
    name: docker
    state: started
    enabled: yes
