---
- name: Update ubuntu package
  apt: 
    update_cache: yes 
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install Dependencies for Ubuntu
  apt:
    name: "{{ item }}"
    state: latest
  loop: [ 'apt-transport-https', 'ca-certificates', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', "gnupg", "lsb-release" ]