---
- name: Install Dependencies for Centos
  become: true
  yum:
    name: "{{ item }}"
    state: latest
  loop: [ "yum-utils", "epel-release", "net-tools", "curl", "wget", "device-mapper-persistent-data", "lvm2", "fuse-overlayfs", "python-docker" ]