---
- name: Install Dependencies for Centos
  become: true
  yum:
    name: "{{ item }}"
    state: latest
  loop: [ 'apt-transport-https', 'ca-certificates', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', "gnupg", "lsb-release" ]

- name: Install Docker Module for Python
  become: true
  pip:
    name: docker
    state: latest